#!/usr/bin/env bash
# script that will display information about subdomains
sub_info ()
{
	domain="$1"
	if [[ -z "$2" ]]; then
		subdomain="www lb-01 web-01 web-02"
	else
		subdomain="$2"
	fi

	for each in $subdomain
	do
		echo -n "The subdomain $each is a "
		dig "$each.$domain" | grep -A1 'ANSWER SECTION:' | sed -n '2 p' | awk '{print $4 " record and points to " $5}'
	done
}

sub_info "$1" "$2"
