#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo sh -c 'echo "Hello World" > /var/www/html/index.nginx-debian.html'
sudo sed -i "/server_name _;/a\\\trewrite ^/redirect_me https://holbertonschool.com.au/ permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
