#!/usr/bin/env bash
# Install MySQL (distribution must be 5.7.x) on web servers
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install wget -y
wget https://dev.mysql.com/get/mysql-apt-config_0.8.12-1_all.deb
sudo dpkg -i mysql-apt-config_0.8.12-1_all.deb
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 467B942D3A79BD29
sudo apt-get update
sudo apt-get install -f mysql-client=5.7* mysql-community-server=5.7* mysql-server=5.7*
